// api/generate-text.js
// NU importăm GoogleGenerativeAI. Folosim fetch simplu.

export default async function handler(req, res) {
  // 1. Configurare CORS (Ca să nu blocheze frontend-ul)
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method Not Allowed' });

  try {
    const { prompt } = req.body;
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
        console.error("Eroare: GEMINI_API_KEY lipseste din Vercel!");
        return res.status(500).json({ error: "Server Configuration Error: Missing API Key" });
    }

    console.log("Attempting manual fetch to Google API...");

    // 2. URL-ul direct către API (Bypass la SDK)
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;

    // 3. Facem cererea HTTP manual
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{
          parts: [{ text: prompt || "Hello" }]
        }]
      })
    });

    const data = await response.json();

    // 4. Verificăm dacă Google ne-a dat eroare
    if (!response.ok) {
      console.error("Google API Raw Error:", JSON.stringify(data, null, 2));
      // Dacă aici e 404, înseamnă că API Key-ul tot nu e bun sau Proiectul e blocat.
      return res.status(response.status).json({ 
          error: data.error?.message || "Google AI Error",
          details: data
      });
    }

    // 5. Extragem textul
    const output = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!output) {
        return res.status(500).json({ error: "No content generated by AI." });
    }

    console.log("Success!");
    return res.status(200).json({ output });

  } catch (error) {
    console.error("Server Internal Error:", error);
    return res.status(500).json({ error: error.message });
  }
}
